# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5446a09ef9469b71f8ca1a5af26679c4045e67de9ae438b8126f08e90af076ca3597f850322984c81b166a63ec6e27f17f5d3d034058914903adf6722fb3ff4c

test:
  secret_key_base: 86f48446afd8b714f30a20614f40357b68fa17dc644ce0fa5a3e1fa7c7a18e271275542da0529a9b1aa8efa455cf1dd59c7658e67254043bb6ab048bc236f8f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
